#!/usr/bin/env bash

# Invoke with:
# 						curl https://raw.githubusercontent.com/kernel-panic-42/bas-dotfiles/main/setup | bash


set -o errexit

# Script-global vars
declare dotfiles="$HOME/.dotfiles"
declare backupdir="$HOME/.backups"

# Make backup of a file (not even sure if backups are really neccessary,
# as this is for a freshly minted dev space.
# Note path chars (/) are turned into dashes.
backup() {
  if [[ -e "$HOME/$1" ]]; then
    local file
    file="$(echo "$1" | tr '\/' '-')"
    cp "$HOME/$1" "$backupdir/$file"
  fi
}

# Bring in and set up dotfiles
setup_dotfiles() {
  rm -rf "$dotfiles"
  git clone https://github.com/kernel-panic-42/bas-dotfiles.git "$dotfiles"
  # ln -s -f "$dotfiles/bashrc" "$HOME/.bashrc"
  # ln -s -f "$dotfiles/bashrc.d" "$HOME/.bashrc.d"
}

setup_dirs() {
  [[ -d "$backupdir" ]] || mkdir "$backupdir"
}

# Install common utilities
# ------------------------

main() {
  setup_dirs
  backup ".bashrc"
  setup_dotfiles
  
  cp "$dotfiles/bash_aliases" "$HOME/.bash_aliases" 
  cp "$dotfiles/bash_functions" "$HOME/.bash_functions" 
}

main "$@"
